/**
 * Created by LiJunnan on 2015/1/29.
 */

exports.rule111Template=
    "\n"
    + "rule ReduceConvert$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience $SALIENCE1$\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.convert($REDUCECONVERT$);\n"
    + "end\n"
    + "\n"
    + "rule Reduce$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience $SALIENCE0$\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.dopackage($REDUCECONFIG$);\n"
    + "end\n"
    + "\n"
    + "rule CouponConvert$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience 501\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.presentConvert($COUPONCONVERT$, $COUPONPOSACCU$);\n"
    + "end\n"
    + "\n"
    + "rule Coupon$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience 500\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.presentPackage($COUPPONCONFIG$, 1, $COUPONPOSACCU$);\n"
    + "end\n"
    + "\n"
    + "rule GiftConvert$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience 301\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.presentConvert($GIFTCONVERT$, $GIFTPOSACCU$);\n"
    + "end\n"
    + "\n"
    + "rule Gift$INTTIME$\n"
    + "    date-effective $DATEEFFECTIVE$\n"
    + "    date-expires $DATEEXPIRES$\n"
    + "    salience 300\n"
    + "    no-loop true\n"
    + "    when\n"
    + "        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    + "    then\n"
    + "        $itemlist.presentPackage($GIFTCONFIG$, 2, $GIFTPOSACCU$);\n"
    + "end\n"
    + "\n"
;

exports.rule110Template=
    "\n"
    +"rule ReduceConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE1$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.convert($REDUCECONVERT$);\n"
    +"end\n"
    +"\n"
    +"rule Reduce$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE0$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.dopackage($REDUCECONFIG$);\n"
    +"end\n"
    +"\n"
    +"rule CouponConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 501\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($COUPONCONVERT$, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Coupon$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 500\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($COUPPONCONFIG$, 1, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
;

exports.rule101Template=
    "\n"
    +"rule ReduceConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE1$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.convert($REDUCECONVERT$);\n"
    +"end\n"
    +"\n"
    +"rule Reduce$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE0$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.dopackage($REDUCECONFIG$);\n"
    +"end\n"
    +"\n"
    +"rule GiftConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 301\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($GIFTCONVERT$, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Gift$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 300\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($GIFTCONFIG$, 2, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
;

exports.rule100Template=
    "\n"
    +"rule ReduceConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE1$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.convert($REDUCECONVERT$);\n"
    +"end\n"
    +"\n"
    +"rule Reduce$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience $SALIENCE0$\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 1, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.dopackage($REDUCECONFIG$);\n"
    +"end\n"
    +"\n"
;

exports.rule011Template=
    "\n"
    +"rule CouponConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 501\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($COUPONCONVERT$, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Coupon$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 500\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($COUPPONCONFIG$, 1, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule GiftConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 301\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($GIFTCONVERT$, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Gift$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 300\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($GIFTCONFIG$, 2, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
;

exports.rule010Template=
    "\n"
    +"rule CouponConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 501\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($COUPONCONVERT$, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Coupon$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 500\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $COUPONVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($COUPPONCONFIG$, 1, $COUPONPOSACCU$);\n"
    +"end\n"
    +"\n"
;

exports.rule001Template=
    "\n"
    +"rule GiftConvert$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 301\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentConvert($GIFTCONVERT$, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
    +"rule Gift$INTTIME$\n"
    +"    date-effective $DATEEFFECTIVE$\n"
    +"    date-expires $DATEEXPIRES$\n"
    +"    salience 300\n"
    +"    no-loop true\n"
    +"    when\n"
    +"        $itemlist: ItemList(flag == 2, vipgrade >= $GIFTVIPGRADE$, deptcode == $DEPTCODE$)\n"
    +"    then\n"
    +"        $itemlist.presentPackage($GIFTCONFIG$, 2, $GIFTPOSACCU$);\n"
    +"end\n"
    +"\n"
;